# render.yaml
services:
  - type: web
    name: job-analytics-portal
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10